routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GenderController;
use App\Http\Controllers\StyleController;
use App\Http\Controllers\LabelController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\BandController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\TrackController;
use App\Http\Controllers\ArtistController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ArtistTrackController;
use App\Http\Controllers\ImagenController;
use App\Http\Controllers\ArtistAlbumController;
use phpDocumentor\Reflection\Types\Boolean;

//HOME


Route::get('/', function () {
    return view('layouts.main');
});

Route::get('/home', function () {
    return view('home');
});

Route::prefix('admin')->group(function () {
    Route::get('/', function () { return view('admin');});
    Route::get('/usuarios', function () { return view('usuarios');});
});

Route::resource('genders', GenderController::class)->names('genders');
Route::resource('genders.styles', StyleController::class)->shallow();
Route::post('/search-styles', [StyleController::class, 'fetch'])->name('search.styles');

Route::resource('labels', LabelController::class)->names('labels');
Route::post('/search-labels', [LabelController::class, 'fetch'])->name('search.label');

Route::resource('countries', CountryController::class)->names('countries');
Route::post('/search-countries', [CountryController::class, 'fetch'])->name('search.fetch');

Route::resource('bands', BandController::class)->names('bands');

/* Vistas */
Route::get('info-bands', [BandController::class,'indexBands'])->name('info-bands');
Route::get('show-bands/{band}', [BandController::class,'showBand'])->name('show-bands');
Route::get('show-album/{album}', [AlbumController::class,'showAlbum'])->name('show-album');

Route::post('/search-bands', [BandController::class, 'fetch'])->name('search.bands');

Route::resource('bands.members', MemberController::class)->shallow();
Route::resource('bands.albums', AlbumController::class)->shallow();


Route::resource('albums.artist_albums', ArtistAlbumController::class)->shallow();

Route::resource('albums.tracks', TrackController::class)->shallow();
Route::resource('tracks.artist_tracks', ArtistTrackController::class)->shallow();

Route::get('info-artists', [ArtistController::class,'indexArtists'])->name('info-artists');
Route::get('show-artists/{artist}', [ArtistController::class,'showArtists'])->name('show-artists');

Route::resource('artists', ArtistController::class)->names('artists');
Route::post('/search-artists', [ArtistController::class, 'fetch'])->name('search.artists');

//Filesystem-disks
Route::get('imagenes/{discs}/{imagen}', ImagenController::class)->name('download_imagen');

/* Route::get('ejemplo', function(){    
})->name('ejemplo'); */

app/Models/Band.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Album;
use App\Models\Country;
use App\Models\Artist;

class Band extends Model
{
    use HasFactory;

    protected $table = 'bands';

    protected $fillable = ['name','start','end','history','imagen','country_id','gender_id'];

    public function artists()
    {
        return $this->belongsToMany(Artist::class, 'members', 'artist_id', 'band_id')->withTimestamps();
    }

    public function albums()
    {
        return $this->hasMany(Album::class, 'band_id');
    }

    public function country()
    {
        return $this->belongsTo(Country::class,'country_id');
    }

    public function members()
    {
        return $this->hasMany(Member::class, 'band_id');
    }

    public function image()
    {
        return $this->morphOne('App\Models\Image', 'imageable');
    }

    public function gender()
    {
        return $this->belongsTo(Gender::class,'gender_id');
    }

}

app/Http/Controllers/ArtistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artist;
use App\Models\Band;
use App\Models\Country;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;


class ArtistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //Filtrado
        $buscar = $request->get('buscar');

        $artists = Artist::where('name', 'like', "%$buscar%")
        ->withCount('albums')
        ->with('country')
        ->orderBy('id','desc')->paginate(5);

        return view('artists.index',compact('artists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        return view('artists.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'country_id' =>   'required|integer',
            'name' =>   'required|max:100|unique:artists,name',
            'profile' =>   'required|max:2000|',
            'day_birth' =>   'nullable|date|',
            'day_death' =>   'nullable|date|',
            'imagenes' => 'nullable|image|mimes:jpeg,png,jpg,svg|max:2048'
        ]);

        $data = $request->all();
        
        if ($request->hasFile('imagenes') && $request->file('imagenes')->isValid()) {

            $data['imagen'] = $request->imagenes->store('','artists');
        }
        /* dd($request->all()); */
        Artist::create($data);

        return redirect()->route('artists.index')->with('artist_store', 'Artist Created');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function show(Artist $artist)
    { 
        $countries = Country::all();
        return view('artists.show', compact('artist','countries'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function edit(Artist $artist)
    {
        $countries = Country::all();

        return view('artists.edit', compact('artist', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Artist $artist)
    {
        $request->validate([
            'country_id' =>  'required|integer',
            'name' =>   'required|max:100|unique:artists,name,' .$artist->id,
            'profile' =>   'required|max:2000|',
            'day_birth' =>   'nullable|date|',
            'day_death' =>   'nullable|date|',
            'imagenes' => 'nullable|image|mimes:jpeg,png,jpg,svg|max:2048'

        ]);

        $data = $request->all();
        unset($data['imagenes']);
        
        if ($request->hasFile('imagenes') && $request->file('imagenes')->isValid()) {
            Storage::disk('bands')->delete($artist->imagen);
            $data['imagen'] = $request->imagenes->store('','artists');
        }

        
        $artist->update($data);
        return redirect()->route('artists.index', $artist)->with('artist_update', 'Artist Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Artist  $artist
     * @return \Illuminate\Http\Response
     */
    public function destroy(Artist $artist)
    {
        /* if($artist->country()->count()){
            return  redirect()->back()->with('artist_destroy', 'Record associated with foreign key');
        } */
        $artist->delete();
        return back()->with('artist_destroy','Artists Deleted');
    }

    public function fetch(Request $request)
    {
        if($request->get('query'))
        {
        $query = $request->get('query');
        return Artist::where('name', 'LIKE', "%$query%")->take(10)->get();
        }
    }

    public function indexArtists(Request $request)
    {
        //Filtrado
        $buscar = $request->get('buscar');

        $artists = Artist::where('name', 'like', "%$buscar%")
        ->withCount('bands')
        ->with('country', 'bands')
        ->orderBy('id', 'desc')->paginate(5);

        /* return $artists; */

        return view('sidebar.artists.index', compact('artists'));
    }
    
    public function showArtists(Request $request, Artist $artist)
    {
        $bands = Band::whereHas('albums', function ( $query) use ($artist){ 

            $query->whereHas('relArtistAlbum', function ( $query) use ($artist){
                $query->where('artist_id', $artist->id);
            });
        })->with(['albums' => function ( $query) use ($artist){ 

            $query->whereHas('relArtistAlbum', function ( $query) use ($artist){
                $query->where('artist_id', $artist->id);
            });
        }])->orderBy('id','asc')->paginate(5);
        /* return $bands; */
           
        return view('sidebar.artists.show',compact('artist','bands'));
    }
}

app/Http/Controllers/BandController.php
<?php

namespace App\Http\Controllers;

use App\Models\AlbumStyle;
use App\Models\Band;
use App\Models\Country;
use App\Models\Gender;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;


class BandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //Filtrado
        $buscar = $request->get('buscar');

        $bands = Band::where('name', 'like', "%$buscar%")
        ->with('country','gender')
        ->withCount('members','albums')
        ->orderBy('id', 'Desc')->paginate(5);
        
        
        return view('bands.index', compact('bands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Band $band)
    {   
        $countries = Country::all();
        $genders = Gender::all();
        return view('bands.create',compact('countries','genders'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'country_id' =>    'required|integer',
            'name' =>   'required|max:50',
            'start' =>   'required|integer|min:1900|max:'.(date('Y')+1),
            'end' =>   'required|integer|min:1900|max:'.(date('Y')+1),
            'history' =>   'nullable|max:4000',
            'imagenes' => 'nullable|image|mimes:jpeg,png,jpg,svg|max:2048',
            'gender_id' =>    'required|integer',
        ]);
        
        $data = $request->all();
        
        if ($request->hasFile('imagenes') && $request->file('imagenes')->isValid()) {

            $data['imagen'] = $request->imagenes->store('','bands');
        }

        Band::create($data);   
        
        return redirect()->route('bands.index')->with('band_store', 'Bands Created');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */
    public function show(Band $band)
    {   
        $countries = Country::all();

        return view('bands.show', compact('band', 'countries'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */
    public function edit(Band $band)
    {
        $countries = Country::all();
        $genders = Gender::all();
        return view('bands.edit',compact('band','countries','genders'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, Band $band)
    {
        $request->validate([
            'country_id' =>  'required',
            'name' =>   'required|max:50',
            'start' =>   'required|integer|min:1900|max:'.(date('Y')+1),
            'end' =>   'required|integer|min:1900|max:'.(date('Y')+1),
            'history' =>   'nullable|max:4000',
            'imagenes' => 'nullable|image|mimes:jpeg,png,jpg,svg|max:2048',
            'gender_id' =>    'required|integer',
        ]);

        $data = $request->all();
        unset($data['imagenes']);
        
        if ($request->hasFile('imagenes') && $request->file('imagenes')->isValid()) {
            Storage::disk('bands')->delete($band->imagen);
            $data['imagen'] = $request->imagenes->store('','bands');
        }

        $band->update($data);

        return redirect()->route('bands.index', $band)->with('band_update', 'Band updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Band  $band
     * @return \Illuminate\Http\Response
     */
    public function destroy(Band $band)
    {
        if($band->albums()->count() | $band->members()->count()){
            return back()->with('band_destroy', 'Record associated with foreign key');
        }
        $band->delete();
        return back()->with('band_destroy','Band Deleted');

        
    }

    public function fetch(Request $request)
    {
        if($request->get('query'))
        {
            $query = $request->get('query');
            $data = Band::where('name', 'LIKE', "%$query%")->take(10)->get();
            
            $output = '<ul class="dropdown-menu" style="display:block; position:relative">';
            foreach($data as $row)
                {
                    $output .= '
                    <li><a href="#" onclick="getElementById(\'band_id\').value = '.$row->id.'; getElementById(\'band_name\').value = '.$row->name.'">'.$row->name.'</a></li>    
                    ';
                }
            $output .= '</ul>';
            echo $output;
        }

     
    }

    public function indexBands(Request $request)
    {
        //Filtrado
        $buscar = $request->get('buscar');

        $bands = Band::whereHas('albums', function ( $query) use ($buscar){ 
                $query->where('name', 'like', "%$buscar%");
                $query->orWhere('year', 'like', "%$buscar%");
        })->with(['albums' => function ( $query) use ($buscar){ 
                $query->where('name', 'like', "%$buscar%");
                $query->orWhere('year', 'like', "%$buscar%");
        }])->with('country')->orderBy('id','asc')->paginate(5);


        return view('sidebar.bands.index', compact('bands'));
    }

    public function showBand(Band $band)
    {
        $albums = $band->albums()->with('styles','labels','images')->orderBy('year')->paginate(5);

        $members = $band->members()->whereHas('relArtist', function ( $query) use ($band){ 
            $query->where('band_id',$band->id);
        })->with(['relArtist.bands'])->orderBy('end')->get();
        
        return view('sidebar.bands.show', compact('band', 'albums','members'));
    }

    
    
}

resources/views/bands/create.blade.php
@extends('layouts.main')

@section('title', 'Create Band')

@section('content')

<div class="card">
    <h5 class="card-header">Create Band</h5>
    <div class="card-body">
        <form method="POST" action="{{route('bands.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">

              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" autocomplete="off">
              @error('name')
              <p class="help is-danger" style="color: red">{{ $message }}</p>
              @enderror
            </div>

            <div class="form-group">
              <label for="autocomplete">Select a Country: </label>
               <input type="text" id="country_name" class="form-control input-lg" placeholder="Enter Country Name" autocomplete="off" />
               <div id="countryList">
               </div>
              @csrf
          <input type="hidden" name="country_id" id="country_id">

          <br>
          <label for="name">Duration</label>
          {{-- Time --}}
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Start</span>
            </div>
      
            <input type="number" class="form-control" placeholder="Insert Start" id="start" name="start" value="{{ old('start') }}" min="1900" max="2021">
      
            @error('start')
              <p class="help is-danger" style="color: red">{{ $message }}</p>
              @enderror
      
            <div class="input-group-prepend">
              <span class="input-group-text">End</span>
            </div>
      
            <input type="number" class="form-control" placeholder="Insert End" id="end" name="end" value="{{ old('end') }}" min="1900" max="2021">
      
            @error('end')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
            @enderror      
          </div>
<br>
          <label for="history">History</label>
          <textarea class="form-control" id="history" name="history" value="{{ old('history') }}"></textarea>
          @error('history')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
            @enderror

      <br>
            <div class="form-group">
              <label for="imagenes">Images</label>
              <input type="file" class="form-control-file" id="imagenes" name="imagenes" accept="img/*">
            </div>
            
      <br>

      <div class="form-group">
        <h3>Add Gender</h3>
            <br>
            {{-- Genders --}}
            <div class="input-group">
              <div class="input-group-prepend">
                <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
            </div>
            <select name="gender_id" class="form-control">
                <option class="hidden" selected disabled>Genders</option>
                @foreach ($genders as $gender)
                  <option value="{{ $gender->id }}">
                    {{ $gender->name }}</option>
                @endforeach
            </select>
        </div>
        @error('gender_id')
          <p class="help is-danger" style="color: red">{{ $message }}</p>
        @enderror

          <div class="modal-footer">
            <a type="button" class="btn btn-success" href="{{ route('bands.index') }}">Back</a>
            <button type="submit" class="btn btn-primary">Save changes</button>
          </div>
        </form>
    </div>
  </div>
    
@endsection

@section('scripts')
       {{-- Libreria JQuery --}}
    
<script>
$(document).ready(function(){

$('#country_name').keyup(function(){ 
       var query = $(this).val();
       if(query != '')
       {
        var _token = $('input[name="_token"]').val();
        $.ajax({
         url:"{{ route('search.fetch') }}",
         method:"POST",
         data:{query:query, _token:_token},
         success:function(data){
          $('#countryList').fadeIn();  
                   $('#countryList').html(data);
         }
        });
       }
   });

   $(document).on('click', 'li', function(){  
       $('#country_name').val($(this).text());  
       $('#countryList').fadeOut();  
   });  

});
</script>
@endsection

resources/views/bands/edit.blade.php
@extends('layouts.main')

@section('title', 'Update Bands')

@section('content')
<br>
  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h2>Edit Bands</h2>
                </div>
                <div class="card-body">
                  <form method="POST" action="{{route('bands.update', $band)}}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
            
                    <div class="form-group">
                    <label for="exampleFormControlSelect1">List Countries</label>

                    <div class="form-group">
                       <input type="text" id="country_name" class="form-control input-lg" placeholder="Country Name" 
                       autocomplete="off" value="{{$band->country->name }}"/>
                       <div id="countryList">
                       </div>
                      @csrf
                  <input type="hidden" name="country_id" id="country_id" value="{{$band->country->id }}">

                    @error('country_id')
                    <p class="help is-danger" style="color: red">{{ $message }}</p>
                    @enderror
                      <label for="name">Name Band</label>
                      <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $band->name )}}">
                      @error('name')
                    <p class="help is-danger" style="color: red">{{ $message }}</p>
                    @enderror
                    </div>

                    <label for="name">Duration</label>
                        {{-- Time --}}
                        <div class="input-group mb-3">
                          <div class="input-group-prepend">
                            <span class="input-group-text">Start</span>
                          </div>
                    
                          <input type="number" class="form-control" placeholder="Insert Start" id="start" name="start" value="{{ old('start', $band->start) }}" min="1900" max="2021">
                    
                          @error('start')
                            <p class="help is-danger" style="color: red">{{ $message }}</p>
                            @enderror
                    
                          <div class="input-group-prepend">
                            <span class="input-group-text">End</span>
                          </div>
                    
                          <input type="number" class="form-control" placeholder="Insert End" id="end" name="end" value="{{ old('end', $band->end) }}" min="1900" max="2021">
                    
                          @error('end')
                          <p class="help is-danger" style="color: red">{{ $message }}</p>
                          @enderror      
                        </div>
                        <br>
                        <label for="history">History</label>
                        <textarea class="form-control" id="history" name="history" value="{{ old('history') }}">{{ $band->history }}</textarea>
                        @error('history')
                          <p class="help is-danger" style="color: red">{{ $message }}</p>
                          @enderror

                    <br>
                          <div class="form-group">
                            <label for="imagenes">Images</label>
                            <input type="file" class="form-control-file" id="imagenes" name="imagenes" accept="img/*">
                          </div>
                          
                    <br>

                    <div class="form-group">
                      <h3>Add Gender</h3>
                          <br>
                          {{-- Genders --}}
                          <div class="input-group">
                            <div class="input-group-prepend">
                              <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
                          </div>
                          <select name="gender_id" class="form-control">
                              <option class="hidden" selected disabled>Genders</option>
                              @foreach ($genders as $gender)
                                <option value="{{ $gender->id }}"
                                  @if ($gender->id === $band->gender_id)
                                    selected
                                  @endif
                                  >
                                  {{ $gender->name }}</option>
                              @endforeach
                          </select>
                      </div>
                      @error('gender_id')
                        <p class="help is-danger" style="color: red">{{ $message }}</p>
                      @enderror
                    
                    <div class="modal-footer">
                      <a type="button" class="btn btn-success" href="{{ route('bands.index') }}">Back</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
       {{-- Libreria JQuery --}}
    

    <script>
$(document).ready(function(){

$('#country_name').keyup(function(){ 
       var query = $(this).val();
       if(query != '')
       {
        var _token = $('input[name="_token"]').val();
        $.ajax({
         url:"{{ route('search.fetch') }}",
         method:"POST",
         data:{query:query, _token:_token},
         success:function(data){
          $('#countryList').fadeIn();  
                   $('#countryList').html(data);
         }
        });
       }
   });

   $(document).on('click', 'li', function(){  
       $('#country_name').val($(this).text());  
       $('#countryList').fadeOut();  
   });  

});

  </script>
@endsection

resources/views/bands/index.blade.php
@extends('layouts.main')

@section('title', 'Bands')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Bands</h1>
    <a href="{{ route('bands.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-user fa-sm text-white-50 Create"></i>Create</a>
</div> 

<nav class="navbar navbar-light float-right mb-4">

  <form class="form-inline">

    <input name="buscar" class="form-control mr-sm-2" type="search" placeholder="Name" aria-label="Search" autocomplete="off">

    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    <a href="{{route('bands.index')}}" class="btn btn-danger my-2 my-sm-2" type="submit">Clear</a>
  </form>

</nav>

<div class="row">
    @include('custom.message')
</div>

<!-- List bands -->
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Bands</th>
        <th scope="col">Albums</th>
        <th scope="col">Countries</th>
        <th scope="col">Start</th>
        <th scope="col">End</th>
        <th scope="col">Members</th>
        <th scope="col">Gender</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     @foreach ($bands as $band)
     <tr>
        <td scope="row">{{ $band->id }}</td>
        <td scope="row"><a href="{{ route('bands.show', $band->id) }}">{{ $band->name }}</a></td>
        <td scope="row">
          <a href="{{ route('bands.albums.index', $band)}}">{{ $band->albums_count}}</a>
        </td>
        <td scope="row">{{ $band->country->name}}</td>
        <td scope="row">{{ $band->start}}</td>
        <td scope="row">{{ $band->end}}</td>
        <td scope="row"><a href="{{ route('bands.members.index', $band) }}">{{ $band->members_count}}</a></td>
        <td scope="row">{{$band->gender->name}}</td>
        <td scope="row"><a href="{{ route('bands.edit', $band) }}" class="btn btn-primary">
        <i class="fa fa-edit"></i>
        </a></td>
        <td scope="row">
        <button class="btn btn-warning btnEliminar" data-id="{{ $band->id }}" data-toggle="modal" data-target="#modalEliminar"><i class="fa fa-trash"></i></button>
          <form action="{{ route('bands.destroy', $band) }}" id="formEli_{{ $band->id}}" method="POST">
            @csrf
           {{-- @method('DELETE') --}}
            <input type="hidden" name="id" value="{{ $band->id }}">
            <input type="hidden" name="_method" value="delete">
            
          </form>
        </td>
      </tr>
     @endforeach
    </tbody>
  </table>
  <span>
    {{ $bands->links() }}
  </span>

<!-- Modals -->
{{-- @include('bands.modalCreate') --}}
@include('bands.modalDelete')
<!-- EndModals -->

@endsection

@section('scripts')
      <script>

        var idEliminar = 0;

          $(document).ready(function(){
            /* @if($message = session('ErrorInsert'))
                $('#Create').modal('show');
            @endif */
            $(".btnEliminar").click(function(){
                idEliminar = $(this).data('id');
            });
            $(".btnModalEliminar").click(function(){
                $("#formEli_" + idEliminar).submit();
            });

          });
      </script>
  @endsection

resources/views/bands/modalCreate.blade.php
<div class="modal fade" id="modalCreate" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create Gender</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{{route('bands.store')}}">
                @csrf
        
                <div class="form-group">
              
                  <div class="form-group">
                      <label for="exampleFormControlSelect1">List Countries</label>
                      <select class="form-control" id="exampleFormControlSelect1" name="country_id">
                          @foreach ($countries as $country)
                            <option value="{{ $country->id }}">{{ $country->name }}</option>
                          @endforeach
                      </select>
                  </div>
  
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
                <span style="color: red">@error('name'){{$message}}@enderror</span>
              </div>
              
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
              </div>
            </form>
        </div>
        
      </div>
    </div>
  </div>