routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GenderController;
use App\Http\Controllers\StyleController;
use App\Http\Controllers\LabelController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\BandController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\TrackController;
use App\Http\Controllers\ArtistController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ArtistTrackController;
use App\Http\Controllers\ImagenController;
use App\Http\Controllers\ArtistAlbumController;
use phpDocumentor\Reflection\Types\Boolean;

//HOME


Route::get('/', function () {
    return view('layouts.main');
});

Route::get('/home', function () {
    return view('home');
});

Route::prefix('admin')->group(function () {
    Route::get('/', function () { return view('admin');});
    Route::get('/usuarios', function () { return view('usuarios');});
});

Route::resource('genders', GenderController::class)->names('genders');
Route::resource('genders.styles', StyleController::class)->shallow();
Route::post('/search-styles', [StyleController::class, 'fetch'])->name('search.styles');

Route::resource('labels', LabelController::class)->names('labels');
Route::post('/search-labels', [LabelController::class, 'fetch'])->name('search.label');

Route::resource('countries', CountryController::class)->names('countries');
Route::post('/search-countries', [CountryController::class, 'fetch'])->name('search.fetch');

Route::resource('bands', BandController::class)->names('bands');

/* Vistas */
Route::get('info-bands', [BandController::class,'indexBands'])->name('info-bands');
Route::get('show-bands/{band}', [BandController::class,'showBand'])->name('show-bands');
Route::get('show-album/{album}', [AlbumController::class,'showAlbum'])->name('show-album');

Route::post('/search-bands', [BandController::class, 'fetch'])->name('search.bands');

Route::resource('bands.members', MemberController::class)->shallow();
Route::resource('bands.albums', AlbumController::class)->shallow();


Route::resource('albums.artist_albums', ArtistAlbumController::class)->shallow();

Route::resource('albums.tracks', TrackController::class)->shallow();
Route::resource('tracks.artist_tracks', ArtistTrackController::class)->shallow();

Route::get('info-artists', [ArtistController::class,'indexArtists'])->name('info-artists');
Route::get('show-artists/{artist}', [ArtistController::class,'showArtists'])->name('show-artists');

Route::resource('artists', ArtistController::class)->names('artists');
Route::post('/search-artists', [ArtistController::class, 'fetch'])->name('search.artists');

//Filesystem-disks
Route::get('imagenes/{discs}/{imagen}', ImagenController::class)->name('download_imagen');

/* Route::get('ejemplo', function(){    
})->name('ejemplo'); */

app/Models/Participation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Participation extends Model
{
    use HasFactory;

    protected $table = 'participations';

    protected $fillable = ['name'];

    public function relArtistsTracks()
    {
        return $this->hasMany(ArtistTrack::class, 'participation_id');
    }

    public function relArtistAlbum()
    {
        return $this->hasMany(ArtistAlbum::class,'participation_id');
    }

}

app/Http/Controllers/ParticipationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artist;
use App\Models\ArtistTrack;
use App\Models\Participation;
use App\Models\Track;
use Illuminate\Http\Request;

class ParticipationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Track $track)
    {
        $artistTrack = $track->relArtistsTracks()->with('relArtist', 'relParticipation')
        ->orderBy('id', 'Desc')->paginate(5);

        $album = $track->albums;
        
        return view('participations.index', compact('artistTrack', 'track','album'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Track $track)
    {
        $artists = Artist::all();
        $participations = Participation::all();
        
        return view('participations.create',compact('track','artists', 'participations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Track $track)
    {   
        /* $request->validate([
        'artist_id' =>  'required|integer',
        'participation_id' =>  'required|integer',
        'name' =>   'required|max:50',
    ]); */

        $track->relArtistsTracks()->create($request->all());
        return redirect()->route('tracks.participations.index', compact( 'track'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Participation  $participation
     * @return \Illuminate\Http\Response
     */
    public function show(Track $track)
    {   

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Participation  $participation
     * @return \Illuminate\Http\Response
     */
    public function edit(Track $track)
    {
        $participations = Participation::all();
        $artists = Artist::all();
        $participation = $track->relArtistsTracks;
        return view('participations.edit', compact('track','participations', 'artists','participation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Participation  $participation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ArtistTrack $artistTrack)
    {   
        $artistTrack->update($request->all());

        return redirect()>route('tracks.participations.index', compact('artistTrack'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Participation  $participation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Participation $participation)
    {


    }
}

resources/views/participations/create.blade.php
@extends('layouts.main')

@section('title', 'Create Participations')

@section('content')

<div class="container-sm">
  <form method="POST" action="{{route('tracks.artist_tracks.store', $track)}}">
    @csrf
    <div class="form-group">
        <h3>Create participations</h3>
            <br>
        {{-- Participations --}}
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
          </div>
          <select name="participation_id" class="form-control">
            <option class="hidden" selected disabled>Participations</option>
            @foreach ($participations as $participation)
              <option value="{{ $participation->id }}">
                {{ $participation->name }}</option>
            @endforeach
        </select>
      </div>
      @error('participation_id')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror

      <br>
            {{-- Artists List --}}
            <div class="form-group">
               <input type="text" id="artist_name" class="form-control input-lg" placeholder="Enter Artist Name" autocomplete="off" />
               <div id="artistsList">
               </div>
              @csrf
          <input type="hidden" name="artist_id" id="artist_id">
            @error('artist_id')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
            @enderror
            <br>
  
  <div class="modal-footer">
    <a href="{{ route('tracks.artist_tracks.index',$track) }}" class="float-right btn btn-success">Back</a>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
  </form>
  
</div>
    
@endsection

@section('scripts')
<script>
  $(document).ready(function(){
  
  $('#artist_name').keyup(function(){ 
         var query = $(this).val();
         if(query != '')
         {
          var _token = $('input[name="_token"]').val();
          $.ajax({
           url:"{{ route('search.artists') }}",
           method:"POST",
           data:{query:query, _token:_token},
           success:function(data){
            var lista = '<ul class="dropdown-menu" style="display:block; position:relative">';
            data.forEach(function(row){ 
              lista += '<li><a href="#" onclick="cambiarArtist(' + row.id +', `' + row.name + '`)">' + row.name + '</a></li>';
            });
            lista += '</ul>';
            $('#artistsList').fadeIn();  
            $('#artistsList').html(lista);
           }
          });
         }
     });
  });

  function cambiarArtist(id, name) {
    $('#artist_name').val(name);
    $('#artist_id').val(id);
    $('#artistsList').fadeOut();
    
  }

  </script>
@endsection

resources/views/participations/edit.blade.php
@extends('layouts.main')

@section('title', 'Update Participation')

@section('content')
<br>
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="card">
              <div class="card-header">
                  <h2>Edit Participation</h2>
              </div>
              <div class="card-body">
                <form method="POST" action="{{route('artist_tracks.update', $artist_track)}}">
                  @csrf
                  @method('PUT')
          
                  {{-- Participations --}}
                  <label for="exampleFormControlSelect1">List Participations</label>
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <div class="input-group-text"><i class="fa fa-map-marker-alt text-info"></i></div>
                      </div>
                      <select name="participation_id" class="form-control">
                        <option class="hidden" selected disabled>Participations</option>
                        @foreach ($participations as $participation)
                          <option value="{{ $participation->id }}"
                            @if ($participation->id === $artist_track->participation_id)
                                selected
                            @endif
                            >
                            {{ $participation->name }}</option>
                        @endforeach
                    </select>
                  </div>
                  @error('participation_id')
                  <p class="help is-danger" style="color: red">{{ $message }}</p>
                  @enderror
                  <br>
                  {{-- Artists List --}}
                  <div class="form-group">
                    <input type="text" id="artist_name" class="form-control input-lg" placeholder="Enter Artist Name" autocomplete="off" value="{{ $artist_track->relArtist->name }}"/>
                    <div id="artistsList">
                    </div>
                   @csrf
               <input type="hidden" name="artist_id" id="artist_id" value="{{ $artists->id }}">
                 @error('artist_id')
                 <p class="help is-danger" style="color: red">{{ $message }}</p>
                 @enderror

                  <div class="modal-footer">
                    <a href="{{ route('tracks.artist_tracks.index', $track) }}" class="btn btn-success">Back</a>
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>

                </form>
              </div>
          </div>
      </div>
  </div>
</div>
@endsection

@section('scripts')
<script>
  artistas = [];
  $(document).ready(function(){
  $('#artist_name').keyup(function(){ 

         var query = $(this).val();
         if(query != '')
         {
          var _token = $('input[name="_token"]').val();
          $.ajax({
           url:"{{ route('search.artists') }}",
           method:"POST",
           data:{query:query, _token:_token},
           success:function(data){
            artistas = data;
            lista = '<ul class="dropdown-menu" style="display:block; position:relative">';
            data.forEach(function(row){ 
            lista += '<li><a href="#" onclick="cambiarArtist(' + row.id +')">' + row.name + '</a></li>';
            });
            lista += '</ul>';
            $('#artistsList').fadeIn();  
            $('#artistsList').html(lista);
           }
          });
         }
     });
  });

  function cambiarArtist(id) {
    var artista = artistas.find(c => {
      return c.id == id;
    });

    $('#artist_name').val(artista.name);
    $('#artist_id').val(id);
    $('#artistsList').fadeOut();

  }
  </script>
@endsection

resources/views/participations/index.blade.php
@extends('layouts.main')

@section('title', 'Participations')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"><a href="{{ route('tracks.show', $track) }}">{{ $track->name }}</a> Participations</h1>
    <a href="{{ route('tracks.artist_tracks.create',$track) }}" class="btn btn-primary">Create</a>
</div> 

<div class="row">
    @include('custom.message')
</div>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('albums.tracks.index', $album) }}">Tracks</a></li>
    <li class="breadcrumb-item" aria-current="page">Participation</li>
    <li class="breadcrumb-item active" aria-current="page">{{ $track->name}}</li>
  </ol>
</nav>

{{-- Search --}}
<nav class="navbar navbar-light float-right mb-4">

  <form class="form-inline">
    <input name="buscar" class="form-control mr-sm-2" type="search" placeholder="Name" aria-label="Search" autocomplete="off">

    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    <a href="{{route('tracks.artist_tracks.index', $track)}}" class="btn btn-danger my-2 my-sm-2" type="submit">Clear</a>
  </form>

</nav>

<!-- List participations -->
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Participations</th>
        <th scope="col">Artist</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     @foreach ($artist_tracks as $participation)
     <tr>
        <td scope="row">{{ $participation->relParticipation->id }}</td>
        <td scope="row">{{ $participation->relParticipation->name }}</td>
        <td scope="row">{{ $participation->relArtist->name }}</td>
        <td scope="row"><a href="{{ route('artist_tracks.edit', $participation) }}" class="btn btn-primary">
        <i class="fa fa-edit"></i>
        </a></td>
        <td scope="row">
        <button class="btn btn-warning btnEliminar" data-id="{{ $participation->id }}" data-toggle="modal" data-target="#modalEliminar"><i class="fa fa-trash"></i></button>
          <form action="{{ route('artist_tracks.destroy', $participation) }}" id="formEli_{{ $participation->id}}" method="POST">
            @csrf
            <input type="hidden" name="id" value="{{ $participation->id }}">
            <input type="hidden" name="_method" value="delete">
            
          </form>
        </td>
      </tr>
     @endforeach
    </tbody>
  </table>
  <span>
    {{ $artist_tracks->links() }}
  </span>

  <div class="modal-footer">
    <a href="{{ route('albums.tracks.index', $album) }}" class="float-left btn btn-success">Back</a>
  </div>

<!-- Modals -->
@include('participations.modalDelete')
<!-- EndModals -->

@endsection

@section('scripts')
      <script>

        var idEliminar = 0;

          $(document).ready(function(){

            $(".btnEliminar").click(function(){
                idEliminar = $(this).data('id');
            });
            $(".btnModalEliminar").click(function(){
                $("#formEli_" + idEliminar).submit();
            });

          });
      </script>
  @endsection

resources/views/participations/modalDelete.blade.php
<div class="modal fade" id="modalEliminar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Participation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
              <h5>Can you delete gender?</h5>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger btnModalEliminar">Delete</button>
              </div>
        </div>
        
      </div>
    </div>
  </div>