routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GenderController;
use App\Http\Controllers\StyleController;
use App\Http\Controllers\LabelController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\BandController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\TrackController;
use App\Http\Controllers\ArtistController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ArtistTrackController;
use App\Http\Controllers\ImagenController;
use App\Http\Controllers\ArtistAlbumController;
use phpDocumentor\Reflection\Types\Boolean;

//HOME


Route::get('/', function () {
    return view('layouts.main');
});

Route::get('/home', function () {
    return view('home');
});

Route::prefix('admin')->group(function () {
    Route::get('/', function () { return view('admin');});
    Route::get('/usuarios', function () { return view('usuarios');});
});

Route::resource('genders', GenderController::class)->names('genders');
Route::resource('genders.styles', StyleController::class)->shallow();
Route::post('/search-styles', [StyleController::class, 'fetch'])->name('search.styles');

Route::resource('labels', LabelController::class)->names('labels');
Route::post('/search-labels', [LabelController::class, 'fetch'])->name('search.label');

Route::resource('countries', CountryController::class)->names('countries');
Route::post('/search-countries', [CountryController::class, 'fetch'])->name('search.fetch');

Route::resource('bands', BandController::class)->names('bands');

/* Vistas */
Route::get('info-bands', [BandController::class,'indexBands'])->name('info-bands');
Route::get('show-bands/{band}', [BandController::class,'showBand'])->name('show-bands');
Route::get('show-album/{album}', [AlbumController::class,'showAlbum'])->name('show-album');

Route::post('/search-bands', [BandController::class, 'fetch'])->name('search.bands');

Route::resource('bands.members', MemberController::class)->shallow();
Route::resource('bands.albums', AlbumController::class)->shallow();


Route::resource('albums.artist_albums', ArtistAlbumController::class)->shallow();

Route::resource('albums.tracks', TrackController::class)->shallow();
Route::resource('tracks.artist_tracks', ArtistTrackController::class)->shallow();

Route::get('info-artists', [ArtistController::class,'indexArtists'])->name('info-artists');
Route::get('show-artists/{artist}', [ArtistController::class,'showArtists'])->name('show-artists');

Route::resource('artists', ArtistController::class)->names('artists');
Route::post('/search-artists', [ArtistController::class, 'fetch'])->name('search.artists');

//Filesystem-disks
Route::get('imagenes/{discs}/{imagen}', ImagenController::class)->name('download_imagen');

/* Route::get('ejemplo', function(){    
})->name('ejemplo'); */

app/Models/Track.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Track extends Model
{
    use HasFactory;

    protected $table = 'tracks';

    protected $fillable = ['name','duration','album_id', 'style_id'];

    protected $appends = ['duration_format'];  //Appending Values To JSON

    public function artists()
    {
        return $this->belongsToMany(Artist::class, 'artist_track', 'artist_id','track_id', 'partipation_id')->withTimestamps();
    }

    public function style()
    {
        return $this->belongsTo(Style::class, 'style_id');
    }

    public function albums()
    {
        return $this->belongsTo(Album::class, 'album_id');
    }

    public function relArtistsTracks()
    {
        return $this->hasMany(ArtistTrack::class, 'track_id');
    }

    /* public function setDurationAttribute($duration)
    {
        $this->attributes['duration'] = ($duration);
    } */

    public function getDurationFormatAttribute() //Accesor
    {
        return date('H:i:s', $this->attributes['duration']);
    }


}

app/Http/Controllers/TrackController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use App\Models\Style;
use App\Models\Track;
use Illuminate\Http\Request;

class TrackController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request,Album $album)
    {
        //Filtrado
        $buscar = $request->get('buscar');

        $tracks = $album->tracks()->where('name', 'like', "%$buscar%")
        ->withCount('relArtistsTracks')->orderBy('id', 'desc')->paginate(5);
 
        $band = $album->bands;
        /* return $tracks; */
        return view('tracks.index ', compact('tracks','album', 'band'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Album $album)
    {
        $styles = Style::all();

        return view('tracks.create', compact('styles','album'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Album $album)
    {
        $request->validate([
            'style_id' =>  'required|integer',
            'name' =>   'required|max:50',
            'hora' => 'nullable|integer|max:2',
            'minutos' => 'nullable|integer|max:60',
            'segundos' => 'nullable|integer|max:60',
        ]);

        $input = $this->calcularTiempo($request);
        
        $album->tracks()->create($input);

        return redirect()->route('albums.tracks.index',compact('album'))->with('track_store','Track Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function show(Track $track)
    {
        $style = $track->style;
        $album = $track->albums;   
        return view('tracks.show', compact('style', 'track', 'album'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,Track $track)
    {   
        $styles = Style::all();
        $album = $track->albums;
        
        $duracion = $track->duration;//devuelve la suma de la operacion del store
        
        $hora = intdiv( $duracion, 3600);   //Devuelve el cociente entero de la división de dividend entre divisor.
        $modHora = $duracion % 3600;//operacion modulo
        $minutos = intdiv($modHora, 60);
        $segundos = $duracion % 60;//operacion modulo

        $hours = $track->hora = $hora;
        $minutes = $track->minutos = $minutos;
        $seconds = $track->segundos = $segundos;

        return view('tracks.edit', compact('track','styles', 'album', 'hours', 'minutes', 'seconds'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Track $track)
    {
        $request->validate([
            'style_id' =>  'required|integer',
            'name' =>   'required|max:50',
            'hora' => 'nullable|integer|max:2',
            'minutos' => 'nullable|integer|max:60',
            'segundos' => 'nullable|integer|max:60',
        ]);

        $input = $this->calcularTiempo($request);

        $track->update($input);
        $album = $track->albums;
       
        return redirect()->route('albums.tracks.index', compact('track', 'album'))->with('track_update','Track Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Track  $track
     * @return \Illuminate\Http\Response
     */
    public function destroy(Track $track)
    {
        /* if($track->albums()->count()){
            return redirect()->back()->with('track_destroy','Record associated with foreign key');  
        } */
        $track->delete();
        return redirect()->back()->with('track_destroy','Track Deleted');
    }

    public function calcularTiempo($request){
        
        $duration = $request->hora * 3600 + $request->minutos * 60 + $request->segundos;
        
        $input = $request->all();//muestra todos los registros en un array

        $input['duration'] = $duration;//agrega elemento al array

        return $input;
    }
}

resources/views/tracks/create.blade.php
@extends('layouts.main')

@section('title', 'Create Tracks')

@section('content')

<div class="container-sm">
  <form method="POST" action="{{route('albums.tracks.store', $album)}}">
    @csrf
    <div class="form-group">
        <h3>Create Tracks</h3>
            <br>
            {{-- Styles List --}}
            <div class="form-group">
              <label for="autocomplete">Select a Styles: </label>
               <input type="text" id="style_name" class="form-control input-lg" placeholder="Enter Style" autocomplete="off" />
               <div id="stylesList">
               </div>
               
          <input type="hidden" name="style_id" id="style_id">
            @error('style_id')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
            @enderror
            <br>
  
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" autocomplete="off">
      @error('name')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror
    </div>

    <label for="name">Duration</label>
    {{-- Time --}}
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text">Hour</span>
      </div>

      <input type="number" class="form-control" placeholder="Insert Hours" id="hora" name="hora" value="{{ old('hora') }}">

      @error('hora')
        <p class="help is-danger" style="color: red">{{ $message }}</p>
        @enderror

      <div class="input-group-prepend">
        <span class="input-group-text">Minutes</span>
      </div>

      <input type="number" class="form-control" placeholder="Insert Minutes" id="minutos" name="minutos" value="{{ old('minutos') }}">

      @error('minutos')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror

      <div class="input-group-prepend">
        <span class="input-group-text">Seconds</span>
      </div>

      <input type="number" class="form-control" placeholder="Insert Seconds" id="segundos" name="segundos" value="{{ old('segundos') }}">

      @error('segundos')
        <p class="help is-danger" style="color: red">{{ $message }}</p>
        @enderror

    </div>
    

  
  <div class="modal-footer">
    <a href="{{ route('albums.tracks.index', $album) }}" class="float-right btn btn-success">Back</a>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
  </form>
  
</div>
    
@endsection

@section('scripts')

<script>
  $(document).ready(function(){
  
  $('#style_name').keyup(function(){ 
         var query = $(this).val();
         if(query != '')
         {
          var _token = $('input[name="_token"]').val();
          $.ajax({
           url:"{{ route('search.styles') }}",
           method:"POST",
           data:{query:query, _token:_token},
           success:function(data){
            $('#stylesList').fadeIn();  
            $('#stylesList').html(data);
           }
          });
         }
     });
  
     $(document).on('click', 'li', function(){  
         $('#style_name').val($(this).text());  
         $('#stylesList').fadeOut();  
     });  
  
  });
  </script>
@endsection

resources/views/tracks/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit Tracks')

@section('content')
<br>

<div class="form-group">
  <form method="POST" action="{{route('tracks.update',$track)}}">
    @csrf
    @method('PUT')
    <h2>Edit Track</h2>
    {{-- Styles List --}}
    <div class="form-group">
      <label for="autocomplete">Select a Styles: </label>
       <input type="text" id="style_name" class="form-control input-lg" placeholder="Enter Label Name" autocomplete="off" value="{{ $track->style->name }}"/>
       <div id="stylesList">
       </div>
      @csrf
  <input type="hidden" name="style_id" id="style_id" value="{{ $track->style->id }}">
    @error('style_id')
    <p class="help is-danger" style="color: red">{{ $message }}</p>
    @enderror
    <br>

    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $track->name) }}" autocomplete="off">
    @error('name')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
    @enderror

    <br>
   {{-- Time --}}
   <label for="name">Duration</label>
   <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Hour</span>
    </div>

    <input type="number" class="form-control" placeholder="Insert Hours" id="hora" name="hora" value="{{ old('hora', $hours)}}">

    @error('hora')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror

    <div class="input-group-prepend">
      <span class="input-group-text">Minutes</span>
    </div>

    <input type="number" class="form-control" placeholder="Insert Minutes" id="minutos" name="minutos" value="{{ old('minutos', $minutes) }}">

    @error('minutos')
    <p class="help is-danger" style="color: red">{{ $message }}</p>
    @enderror

    <div class="input-group-prepend">
      <span class="input-group-text">Seconds</span>
    </div>

    <input type="number" class="form-control" placeholder="Insert Seconds" id="segundos" name="segundos" value="{{ old('segundos', $seconds) }}">

    @error('segundos')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror

  </div>
    
    <div class="modal-footer">
      <a href="{{ route('albums.tracks.index', $album) }}" class="float-right btn btn-success">Back</a>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
  
</div>
  
@endsection

@section('scripts')
<script>
  $(document).ready(function(){
  
  $('#style_name').keyup(function(){ 
         var query = $(this).val();
         if(query != '')
         {
          var _token = $('input[name="_token"]').val();
          $.ajax({
           url:"{{ route('search.styles') }}",
           method:"POST",
           data:{query:query, _token:_token},
           success:function(data){
            $('#stylesList').fadeIn();  
            $('#stylesList').html(data);
           }
          });
         }
     });
  
     $(document).on('click', 'li', function(){  
         $('#style_name').val($(this).text());  
         $('#stylesList').fadeOut();  
     });  
  
  });
  </script>
@endsection

resources/views/tracks/index.blade.php
@extends('layouts.main')

@section('title', 'List Tracks')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"><a href="{{ route('albums.show', $album) }}">{{ $album->name }}</a> Tracks</h1>
    <a href="{{ route('albums.tracks.create', $album) }}" class="btn btn-primary">Create</a>
</div> 

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('bands.albums.index', $band) }}">Albums</a></li>
    <li class="breadcrumb-item" aria-current="page">Tracks</li>
    <li class="breadcrumb-item active" aria-current="page">{{ $album->name}}</li>
  </ol>
</nav>

<nav class="navbar navbar-light float-right mb-4">

  <form class="form-inline">

    <input name="buscar" class="form-control mr-sm-2" type="search" placeholder="Name" aria-label="Search" autocomplete="off">

    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    <a href="{{route('albums.tracks.index', $album)}}" class="btn btn-danger my-2 my-sm-2" type="submit">Clear</a>
  </form>

</nav>

<div class="row">
    @include('custom.message')
</div>

<!-- List Tracks -->
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Tracks</th>
        <th scope="col">Duration</th>
        <th scope="col">Style</th>
        <th scope="col">Participation</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     @foreach ($tracks as $track)
     <tr>
        <td scope="row">{{ $track->id }}</td>
        <td scope="row"><a href="{{ route('tracks.show', $track->id) }}">{{ $track->name }}</a></td>
        <td scope="row">{{ $track->duration_format }}</td>
        <td scope="row">{{ $track->style->name }}</td>
        <td scope="row"><a href="{{ route('tracks.artist_tracks.index', $track) }}">{{ $track->rel_artists_tracks_count }}</a></td>
        <td scope="row"><a href="{{ route('tracks.edit',$track) }}" class="btn btn-primary">
        <i class="fa fa-edit"></i>
        </a></td>
        <td scope="row">
        <button class="btn btn-warning btnEliminar" data-id="{{ $track->id }}" data-toggle="modal" data-target="#modalEliminar"><i class="fa fa-trash"></i></button>
          <form action="{{ route('tracks.destroy', $track) }}" id="formEli_{{ $track->id}}" method="POST">
            @csrf
            <input type="hidden" name="id" value="{{ $track->id }}">
            <input type="hidden" name="_method" value="delete">
            
          </form>
        </td>
      </tr>
     @endforeach
    </tbody>
  </table>
  <span>
    {{ $tracks->links() }}
  </span>

<div class="modal-footer">
  <a href="{{ route('bands.albums.index', $band) }}" class="float-left btn btn-success">Back</a>
</div>
<!-- Modals -->
{{-- @include('Tracks.modalCreate') --}}
@include('Tracks.modalDelete')
<!-- EndModals -->

@endsection

@section('scripts')
      <script>

        var idEliminar = 0;

          $(document).ready(function(){
            $(".btnEliminar").click(function(){
                idEliminar = $(this).data('id');
            });
            $(".btnModalEliminar").click(function(){
                $("#formEli_" + idEliminar).submit();
            });

          });
      </script>
  @endsection

resources/views/tracks/modalDelete.blade.php
<div class="modal fade" id="modalEliminar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Track</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
              <h5>Can you delete track?</h5>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger btnModalEliminar">Delete</button>
              </div>
        </div>
        
      </div>
    </div>
  </div>

resources/views/tracks/show.blade.php
@extends('layouts.main')

@section('title', 'Show Track')

@section('content')

<div class="card">
    <h5 class="card-header">Show Track</h5>
    <div class="card-body">
        <form>
            @csrf
            <div class="form-group">
              
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Styles</label>
                    <input type="text" class="form-control" id="style_id" name="style_id" value="{{ old('style_id', $style->name) }}" disabled>
                </div>

              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $track->name) }}" disabled>
            </div>
            <label for="name">Duration</label>
              <input type="text" class="form-control" id="duration" name="duration" value="{{ old('duration', $track->duration) }}" disabled>
            </div>
          
          <div class="modal-footer">
            <a type="button" class="btn btn-success" href="{{ route('albums.tracks.index', $album)}}">Back</a>
          </div>
        </form>
    </div>
  </div>
    
@endsection