routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GenderController;
use App\Http\Controllers\StyleController;
use App\Http\Controllers\LabelController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\BandController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\TrackController;
use App\Http\Controllers\ArtistController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\ArtistTrackController;
use App\Http\Controllers\ImagenController;
use App\Http\Controllers\ArtistAlbumController;
use phpDocumentor\Reflection\Types\Boolean;

//HOME


Route::get('/', function () {
    return view('layouts.main');
});

Route::get('/home', function () {
    return view('home');
});

Route::prefix('admin')->group(function () {
    Route::get('/', function () { return view('admin');});
    Route::get('/usuarios', function () { return view('usuarios');});
});

Route::resource('genders', GenderController::class)->names('genders');
Route::resource('genders.styles', StyleController::class)->shallow();
Route::post('/search-styles', [StyleController::class, 'fetch'])->name('search.styles');

Route::resource('labels', LabelController::class)->names('labels');
Route::post('/search-labels', [LabelController::class, 'fetch'])->name('search.label');

Route::resource('countries', CountryController::class)->names('countries');
Route::post('/search-countries', [CountryController::class, 'fetch'])->name('search.fetch');

Route::resource('bands', BandController::class)->names('bands');

/* Vistas */
Route::get('info-bands', [BandController::class,'indexBands'])->name('info-bands');
Route::get('show-bands/{band}', [BandController::class,'showBand'])->name('show-bands');
Route::get('show-album/{album}', [AlbumController::class,'showAlbum'])->name('show-album');

Route::post('/search-bands', [BandController::class, 'fetch'])->name('search.bands');

Route::resource('bands.members', MemberController::class)->shallow();
Route::resource('bands.albums', AlbumController::class)->shallow();


Route::resource('albums.artist_albums', ArtistAlbumController::class)->shallow();

Route::resource('albums.tracks', TrackController::class)->shallow();
Route::resource('tracks.artist_tracks', ArtistTrackController::class)->shallow();

Route::get('info-artists', [ArtistController::class,'indexArtists'])->name('info-artists');
Route::get('show-artists/{artist}', [ArtistController::class,'showArtists'])->name('show-artists');

Route::resource('artists', ArtistController::class)->names('artists');
Route::post('/search-artists', [ArtistController::class, 'fetch'])->name('search.artists');

//Filesystem-disks
Route::get('imagenes/{discs}/{imagen}', ImagenController::class)->name('download_imagen');

/* Route::get('ejemplo', function(){    
})->name('ejemplo'); */

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;



class Album extends Model
{
    use HasFactory;

    protected $table = 'albums';

    protected $fillable = ['name','year','imagen','label_id','band_id'];

    
    public function styles()
    {
        return $this->belongsToMany(Style::class, 'album_style', 'album_id', 'style_id')->withTimestamps();
    }

    public function labels()
    {
        return $this->belongsTo(Label::class,'label_id');
    }

    public function tracks()
    {
        return $this->hasMany(Track::class, 'album_id');
    }

    public function bands()
    {
        return $this->belongsTo(Band::class, 'band_id');
    }

    public function albumstyle()
    {
        return $this->hasMany(AlbumStyle::class, 'album_id');
    }

    public function images()
    {
        return $this->morphMany('App\Models\Image', 'imageable');
    }

    public function artists()
    {
        return $this->belongsToMany(Artist::class,'artist_album','artist_id', 'album_id')->withTimestamps();
    }

    public function relArtistAlbum()
    {
        return $this->hasMany(ArtistAlbum::class, 'album_id');
    }
    

}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use App\Models\Artist;
use App\Models\Band;
use App\Models\Label;
use App\Models\Style;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request,Band $band)
    {
         //Filtrado
         $buscar = $request->get('buscar');

        $albums = $band->albums()->where('name', 'like', "%$buscar%")
        ->withCount('tracks','relArtistAlbum')->orderBy('id', 'desc')->paginate(5);
        
        
        return view('albums.index', compact('albums', 'band'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Band $band)
    {   
        $labels = Label::all();
        $styles = Style::all();
        return view('albums.create', compact('band','labels','styles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Band $band)
    {
        /* dd($request->all()); */
        $request->validate([
            'label_id' =>  'required|integer',
            'name' =>   'required|max:50',
            'year' =>   'required|digits:4|integer|min:1900|max:'.(date('Y')+1),
            'imagenes' => 'nullable|image|mimes:jpeg,png,jpg,svg|max:2048'
        ]);

        $data = $request->all();
        
        if ($request->hasFile('imagenes') && $request->file('imagenes')->isValid()) {

            $data['imagen'] = $request->imagenes->store('','albums');
        }

        
        $album = $band->albums()->create($data);
        $album->styles()->attach($request->style);
        
        
        return redirect()->route('bands.albums.index', compact('band'))->with('album_store', 'Album Created');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {   
        $band = $album->bands;

        return view('albums.show', compact('album','band'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $album)
    {   
        $labels = Label::all();
        $styles = Style::all();
        $band = $album->bands;

        $album_style=[];

        foreach($album->styles as $style){
            $album_style[] = $style->id;
        }
        return view('albums.edit', compact('album', 'labels', 'band', 'styles','album_style'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $album)
    {
        $request->validate([
            'label_id' =>   'required|integer',
            'name' =>   'required|max:50',
            'year' =>   'required|digits:4|integer|min:1900|max:'.(date('Y')+1),
            'imagenes' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        $data = $request->all();
        unset($data['imagenes']);
        
        if ($request->hasFile('imagenes') && $request->file('imagenes')->isValid()) {
            Storage::disk('albums')->delete($album->imagen);
            $data['imagen'] = $request->imagenes->store('','albums');
        }
        
        $album->update($data);

        $album->styles()->sync($request->style);     

        $band = $album->bands;
        return redirect()->route('bands.albums.index',compact('band'))->with('album_update', 'Album Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $album)
    {
        if($album->tracks()->count() | $album->albumstyle()->count() | $album->relArtistAlbum()->count()){
            return redirect()->back()->with('album_destroy', 'Record associated with foreign key');
        }

        $album->delete();
        return redirect()->back()->with('album_destroy','Album Deleted');
    }

    public function showAlbum(Request $request,Album $album)
    {
        /* return $album; */
        $id=1;
        $tracks = $album->tracks;
        $var =  $album->tracks->sum('duration');

        /* $artists = Artist::whereHas('members', function ( $query) use ($album){  
            $query->where('init','<=', $album->year)
            ->where('end', '>=',$album->year)
            ->where('band_id', $album->band_id );
            })->with([ 
                'members' =>  function ( $query) use ($album) {  
                    $query->where('init','<=', $album->year)
                    ->where('end', '>=',$album->year)
                    ->where('band_id', $album->band_id );
                }, 'relArtistAlbum.relArtist' ])
            ->get(); */
            
        /* $members = $album->relArtistAlbum()->with('relArtist','relParticipation')->orderBy('id','desc')->paginate(5); */
            $members = Artist::whereHas('relArtistAlbum', function ( $query) use ($album){ 

                $query->where('album_id',$album->id);
                
                })->with(['relArtistAlbum' => function ( $query) use ($album){ 

                    $query->where('album_id',$album->id);
                    $query->with('relParticipation');
                    }

                ])
                ->orderBy('name')->get();

        return view('sidebar.bands.albums',compact('album', 'tracks', 'var', 'id', 'members'));
    }

}

resources/views/albums/create.blade.php
@extends('layouts.main')

@section('title', 'Create Album')

@section('content')
    

<div class="container-sm">
  <form method="POST" action="{{route('bands.albums.store', $band)}}" enctype="multipart/form-data">
    @csrf
    <div class="form-group">            
            <div class="form-group">
              <label for="autocomplete">Select a Label: </label>
               <input type="text" id="label_name" class="form-control input-lg" placeholder="Enter Label Name" autocomplete="off" />
               <div id="albumsList">
               </div>
              @csrf
          <input type="hidden" name="label_id" id="label_id">
            @error('label_id')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
            @enderror
            <br>

      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" autocomplete="off">
      @error('name')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror
  
      <label for="name">Year</label>
      <input type="number" class="form-control" id="year" name="year" value="{{ old('year') }}">
      @error('year')
            <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror
    </div>
<br>
      <div class="form-group">
        <label for="imagenes">Images</label>
        <input type="file" class="form-control-file" id="imagenes" name="imagenes" accept="img/*">
      </div>
      
<br>
    <label for="myCheck">Styles:</label>
    <input type="checkbox" id="myCheck" onclick="myFunction()">

      <div class="container" id="text" style="display:none">
        <div class="row row-cols-3">
          @foreach ($styles as $style)
            <div class="col"> <input type="checkbox" name="style[]" id="style_{{ $style->id }}" value="{{ $style->id }}"
              @if (is_array(old('style')) && in_array("$style->id", old('style'))  )
                checked
            @endif
              > {{ $style->name }}</div>
          @endforeach
        </div>
      </div>
    <br>
</div>
  
  
  <div class="modal-footer">
    <a href="{{ route('bands.albums.index', $band) }}" class="float-right btn btn-success">Back</a>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
  </form> 
</div>
    
@endsection

@section('scripts')
  <script>
    function myFunction() {
      var checkBox = document.getElementById("myCheck");
      var text = document.getElementById("text");
      if (checkBox.checked == true){
        text.style.display = "block";
      } else {
        text.style.display = "none";
      }
    }
    </script>
    <script>
      $(document).ready(function(){
      
      $('#label_name').keyup(function(){ 
             var query = $(this).val();
             if(query != '')
             {
              var _token = $('input[name="_token"]').val();
              $.ajax({
               url:"{{ route('search.label') }}",
               method:"POST",
               data:{query:query, _token:_token},
               success:function(data){
                $('#albumsList').fadeIn();  
                $('#albumsList').html(data);
               }
              });
             }
         });
      
         $(document).on('click', 'li', function(){  
             $('#label_name').val($(this).text());  
             $('#albumsList').fadeOut();  
         });  
      
      });
      </script>
@endsection

resources/views/albums/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit albums')

@section('content')
<br>

<div class="form-group">
  <form method="POST" action="{{route('albums.update',$album)}}"  enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <h2>Edit Album</h2>
    {{-- Labels List --}}
    <div class="form-group">            
      <div class="form-group">
         <input type="text" id="label_name" class="form-control input-lg" placeholder="Enter Label Name" autocomplete="off" value="{{ $album->labels->name }}"/>
         <div id="albumsList">
         </div>
        @csrf
    <input type="hidden" name="label_id" id="label_id" value="{{ $album->labels->id }}" >
      @error('label_id')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
      @enderror
      <br>
    <br>

    <label for="name">Name</label>
    <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $album->name) }}" autocomplete="off">
    @error('name')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
    @enderror

    <label for="name">Year</label>
    <input type="number" class="form-control" id="year" name="year" value="{{ old('year', $album->year) }}">
    </div>
    @error('year')
      <p class="help is-danger" style="color: red">{{ $message }}</p>
    @enderror

    <br>
    <div class="form-group">
      <label for="imagenes">Images</label>
      <input type="file" class="form-control-file" id="imagenes" name="imagenes" accept="img/*">
    </div>
    
<br>

    <div class="container" id="text" {{-- style="display:none" --}}>
      <div class="row row-cols-3">
        @foreach ($styles as $style)
          <div class="col"> <input type="checkbox" name="style[]"  id="style_{{ $style->id }}" 
            value="{{ $style->id }}"
            @if (is_array(old('style')) && in_array("$style->id", old('style'))  )
                checked
            @elseif (is_array($album_style) && in_array("$style->id", $album_style)  )
              checked
            @endif>
            {{ $style->name }}</div>
        @endforeach
      </div>
    </div>
  <br>
</div>
    
    <div class="modal-footer">
      <a href="{{ route('bands.albums.index', $band) }}" class="float-right btn btn-success">Back</a>
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
  
</div>
  
@endsection

@section('scripts')
<script>
  $(document).ready(function(){
  
  $('#label_name').keyup(function(){ 
         var query = $(this).val();
         if(query != '')
         {
          var _token = $('input[name="_token"]').val();
          $.ajax({
           url:"{{ route('search.label') }}",
           method:"POST",
           data:{query:query, _token:_token},
           success:function(data){
            $('#albumsList').fadeIn();  
            $('#albumsList').html(data);
           }
          });
         }
     });
  
     $(document).on('click', 'li', function(){  
         $('#label_name').val($(this).text());  
         $('#albumsList').fadeOut();  
     });  
  
  });
  </script>
@endsection

resources/views/albums/index.blade.php
@extends('layouts.main')

@section('title', 'Albums')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800"><a href="{{ route('bands.show',$band) }}">{{ $band->name }}</a> Albums</h1>
    <a href="{{ route('bands.albums.create', $band) }}" class="btn btn-primary">Create</a>
</div> 

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ route('bands.index') }}">Band</a></li>
    <li class="breadcrumb-item" aria-current="page">Albums</li>
    <li class="breadcrumb-item active" aria-current="page">{{ $band->name}}</li>
  </ol>
</nav>

<nav class="navbar navbar-light float-right mb-4">

  <form class="form-inline">

    <input name="buscar" class="form-control mr-sm-2" type="search" placeholder="Name" aria-label="Search" autocomplete="off">

    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    <a href="{{route('bands.albums.index', $band)}}" class="btn btn-danger my-2 my-sm-2" type="submit">Clear</a>
  </form>

</nav>

<div class="row">
    @include('custom.message')
</div>

<!-- List albums -->
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Albums</th>
        <th scope="col">Tracks</th>
        <th scope="col">Year</th>
        <th scope="col">Artist</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     @foreach ($albums as $album)
     <tr>
        <td scope="row">{{ $album->id }}</td>
        <td scope="row"><a href="{{ route('albums.show', $album->id) }}">{{ $album->name }}</a></td>
        <td scope="row"><a href="{{ route('albums.tracks.index', $album) }}">{{ $album->tracks_count }}</a></td>
        <td scope="row">{{ $album->year }}</td>
        <td scope="row"><a href="{{ route('albums.artist_albums.index',$album) }}">{{ $album->rel_artist_album_count }}</a></td>
        <td scope="row"><a href="{{ route('albums.edit', $album) }}" class="btn btn-primary">
        <i class="fa fa-edit"></i>
        </a></td>
        <td scope="row">
        <button class="btn btn-warning btnEliminar" data-id="{{ $album->id }}" data-toggle="modal" data-target="#modalEliminar"><i class="fa fa-trash"></i></button>
          <form action="{{ route('albums.destroy', $album) }}" id="formEli_{{ $album->id}}" method="POST">
            @csrf
            <input type="hidden" name="id" value="{{ $album->id }}">
            <input type="hidden" name="_method" value="delete">
            
          </form>
        </td>
      </tr>
     @endforeach
    </tbody>
  </table>
  <span>
    {{ $albums->links() }}
  </span>

<div class="modal-footer">
  <a href="{{ route('bands.index') }}" class="float-left btn btn-success">Back</a>
</div>
<!-- Modals -->
{{-- @include('albums.modalCreate') --}}
@include('albums.modalDelete')
<!-- EndModals -->

@endsection

@section('scripts')
      <script>

        var idEliminar = 0;

          $(document).ready(function(){
            $(".btnEliminar").click(function(){
                idEliminar = $(this).data('id');
            });
            $(".btnModalEliminar").click(function(){
                $("#formEli_" + idEliminar).submit();
            });

          });
      </script>
  @endsection

resources/views/albums/modalDelete.blade.php
<div class="modal fade" id="modalEliminar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Album</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                  <h5>Can you delete album?</h5>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-danger btnModalEliminar">Delete</button>
                  </div>
            </div>
            
          </div>
        </div>
      </div>

resources/views/albums/show.blade.php
@extends('layouts.main')

@section('title', 'Show Album')

@section('content')

<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">{{ $album->bands->name}}</h1>
</div> 

<div class="card">
    <div class="card-body">
        <h4>Album</h4>
        <br>

        <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $album->name) }}">
            @error('name')
              <p class="help is-danger" style="color: red">{{ $message }}</p>
            @enderror

        <label for="name">Year</label>
            <input type="number" class="form-control" id="year" name="year" value="{{ old('year', $album->year) }}">
            @error('year')
              <p class="help is-danger" style="color: red">{{ $message }}</p>
          @enderror
    </div>
  </div>
  <br>
  <a href="{{ route('bands.albums.index', $band) }}" class="float-left btn btn-success">Back</a>
</div>
@endsection